### ISSUE TITLE
Deploy Kubernetes cluster using ArgoCD

### ISSUE THREAD

**Issue by stvoutsin** [lsst-uk/rsp-uk#17]
After talking to the LSST team, they recommended the deploymeng of K8s using ArgoCD which is what they currently use:
https://argoproj.github.io/argo-cd/

Task is to investigate and if appropriate, deploy using ArgoCD on the Openstack (Edinburgh) cloud.

**Comment by markgbeckett** [comment]
Hi Stelios, Does ArgoCD play the same role as Rancher does currently? If so, it would be interesting to know a little about the differences. Currently, most LSST:UK clusters are deployed with Rancher, which--in fact--is a stop-gap until Magnum is available on sites. George.

**Comment by stvoutsin** [comment]
Hi George, 

To be honest I'm not sure what ArgoCD does yet, it was mentioned during my discussions with the LSSTC team, where they recommended we use it , as that is what they are using currently. However I'm not sure if it's used for deploying LSP on Kubernetes, or just creating a Kubernetes instance. SO initial subtask here would probably be a few days to investigate what it is and does and if it could be useful to us. I have also been using Magnum for deploying K8s on a different project, so it will be interesting to compare.
