### ISSUE TITLE
Deploy customized version of Firefly

### ISSUE THREAD

**Issue by stvoutsin** [lsst-uk/rsp-uk#27]
Deploy customized version of Firefly, with the list of TAP Services modified. Have one of the WFAU TAP services preselected. We can start with the WSA TAP service (http://tap.roe.ac.uk/wsa) for the first experiment

**Comment by markgbeckett** [comment]
Progress made. One remaining element of blockage is configuration of the Admin password. Reported to US team and hope for resolution in w/b 1st March.
