### ISSUE TITLE
Integrate Qserv to UK RSP

### ISSUE THREAD

**Issue by stvoutsin** [lsst-uk/rsp-uk#37]
- [x] Confirm Qserv is working -- e.g., by running suitable queries from the benchmark suite, via the SQL interface
- [x] Confirm how to configure built-in TAP service to link to Qserv instance (N.B., TAP service is configured to use Google Cloud Storage. Need to check if can replace with different storage option).
- [x] Configure TAP service to link to Qserv, and test.
- [ ] Advertise to early-access users.

**Comment by markgbeckett** [comment]
Qserv is running. Craig to provide credentials for Qserv instance, for use in RSP.

**Comment by markgbeckett** [comment]
- Stelios has integrated Qserv into RSP (Synchronous queries only). 
- Steios investigating how to enable synchronous TAP support. Current version of code looks not to support Docker Compose (so difficult to run local development version of code). Despite this, Stelios believe has identified where code changes are needed to support NFS (with caveat that temp files need a URL, even if on NFS, so perhaps use HTTP web server, noting would need to think about security implications). Alternative is to set up S3 object storage.
- Initial impression is that we could tackle this, if was of interest to SQuaRE team.

**Comment by markgbeckett** [comment]
SQuaRE team believe this is possible to do, and would be easier with a development environment (SQuaRE team is simplifying set up to development environment). Stelios keen to try Swift, which is available on UK DAC.

James Perry has previously generalised Rucio for multiple objects stores (GCS, S3 or Swift) based on pre-signed URLs.

**Comment by markgbeckett** [comment]
Work to submit queries from Firefly requires asynchronous support, but TAP not compatible with current UK O/S options.
