### ISSUE TITLE
Deploy RSP using ArgoCD

### ISSUE THREAD

**Issue by stvoutsin** [lsst-uk/rsp-uk#52]

**Comment by markgbeckett** [comment]
- RSP deployed and various bugs reported to SQRE team for resolution.
- Seeing issue with ?authentication using GitHub credentials?

**Comment by markgbeckett** [comment]
Close to done. One outstanding issue to resolve, with admin password for Firefly (with US team for resolution).

**Comment by markgbeckett** [comment]
@gpfrancis will test drive deployment, by creating a further instance of RSP following @stvoutsin's directions.
