### ISSUE TITLE
Deploy Vault Service

### ISSUE THREAD

**Issue by stvoutsin** [lsst-uk/rsp-uk#53]
Deploy Vault Service for Storing secrets
https://www.vaultproject.io/docs/platform/k8s

**Comment by markgbeckett** [comment]
@stvoutsin will review @gpfrancis's notes on deploying a UK-based Vault Service.

**Comment by gpfrancis** [comment]
Deployment notes are here: https://raw.githubusercontent.com/lsst-uk/rsp-uk/master/notes/vault_install_notes_20210201.txt

**Comment by stvoutsin** [comment]
Notes look good to me. Now that we know how to deploy, do we close this issue and create a new one for connecting the RSP deployment to our Vault. (This requires a standard IP/hostname for the Vault that we can add to our configuration)

**Comment by markgbeckett** [comment]
> 
> 
> Notes look good to me. Now that we know how to deploy, do we close this issue and create a new one for connecting the RSP deployment to our Vault. (This requires a standard IP/hostname for the Vault that we can add to our configuration)

Hi Stelios. There is already a ticket, in the To-do, for moving our RSP to use the local Vault service, so we can just close this ticket.
