### ISSUE TITLE
Determine how to make TAP service work properly

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/rsp-uk#58]
Configured to use Google Cloud Storage, so need to determine if can substitute alternative source (c.f., work on IN2P3).

**Comment by markgbeckett** [comment]
Stelios has begun discussions with SQuaRE team. Looks to be complicated.

**Comment by markgbeckett** [comment]
Stelios is trying to set up RSP development environment, so that he can investigate options to general TAP temporary-storage provision.
SQuaRE team has provided some guidance, based on using Minikube, but this is proving challenging to set up.

**Comment by markgbeckett** [comment]
Option to us Swift O/S or to set up Apache web server to front an NFS mount. If RSP is using S3 API, then would probably be better to use Swift.

**Comment by markgbeckett** [comment]
Stelios has been helping Gabriel Mainetti (IN2P3) to deploy RSP on OpenStack. IN2P3 team has similar concerns about Google Cloud Storage dependency and has prototyped an alternative implementation using AWS S3 interface to OpenStack Swift. Plan to mirror this on UK deployment.
