### ISSUE TITLE
Evaluate the use of Butler in the RSP using NFS storage for storing the data repository

### ISSUE THREAD

**Issue by stvoutsin** [lsst-uk/rsp-uk#63]
Initial experiment has been done with Gen 2, we need to experiment with Gen 3 butler.
Store data repository on an NFS share, and experiment with accessing it via notebooks (Nublado)

**Comment by markgbeckett** [comment]
Stelios has investigated various tutorials. Initially https://pipelines.lsst.io/v/daily/install/newinstall.html#newinstall-run. This tutorial did not work, though did succeed using an LSST install pacakge - https://community.lsst.org/t/lsstinstall-available-for-beta-test/6193.

1. Ran demo (https://pipelines.lsst.io/v/daily/install/demo.html), using a single image from HSC data, to validate that Butler setup was correct. This demo sets up a SQLlite database for butler and ingests image from HSC, modifying it to be compatible with Butler.
2. Once succeeded migrated test into UK RSP.
3. Finally, ran a Gen 3 tutorial notebook **(https://github.com/LSSTScienceCollaborations/StackClub/blob/master/Basics/Gen3ButlerTutorial.ipynb)** to confirm was working.

Have an NFS mount, with LSST stack (Gen 3) set up. You have ingested an HSC image into Butler datastore and then accessed that image from a Nublado notebook.

**Comment by markgbeckett** [comment]
@stvoutsin and @MikeeRead  to review progress (Stelios to copy the Butler repository into a file space that Mike can access).
